-- Store Management System
-- PostgreSQL schema for Render

CREATE TABLE IF NOT EXISTS product (
    product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    quantity INTEGER NOT NULL,
    min_stock_level INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS bill (
    bill_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_date TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    total_amount NUMERIC(10,2) DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS bill_item (
    bill_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(10,2) NOT NULL,
    subtotal NUMERIC(10,2) NOT NULL,

    CONSTRAINT bill_item_bill_id_fkey
        FOREIGN KEY (bill_id)
        REFERENCES bill(bill_id),

    CONSTRAINT bill_item_product_id_fkey
        FOREIGN KEY (product_id)
        REFERENCES product(product_id)
);

CREATE TABLE IF NOT EXISTS stock_movement (
    movement_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL,
    change_type VARCHAR(20) NOT NULL,
    quantity INTEGER NOT NULL,
    reference_id INTEGER,
    moved_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    note VARCHAR(255),

    CONSTRAINT stock_movement_product_id_fkey
        FOREIGN KEY (product_id)
        REFERENCES product(product_id)
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
